apiVersion: v1
kind: Service
metadata:
  name: webr-service
  labels:
    run: rach6120
spec:
 # externalTrafficPolicy: Local #addition      #addition 1212
  clusterIP: None
  ports:
  #- port: 8081
  # name: webr-two
  - port: 8080
    name: webr
  selector:
   run: rach6120
---
apiVersion: v1
kind: Service
metadata:
  name: rach6120
  labels:
    app: rach6120
spec:
  type: NodePort
  ports:
  #- port: 8081
   # nodePort: 30375
   # protocol: TCP
   # targetPort: 8081
   # name: webr-two
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: webr
  selector:
    app: rach6120
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webr
  labels:
    app: rach6120
spec:
  serviceName: "webr-service"
  podManagementPolicy: Parallel # Default is OrderedReady
  replicas: 10 # Default is 1
  selector:
    matchLabels:
      app: rach6120 # Has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: rach6120 # Has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: webr-service
        image: rach6120:latest
        imagePullPolicy: Never #changed 120919
        ports:
        - containerPort: 8080
          name: webr
        volumeMounts:
        - name: webr-persistent-storage
          mountPath: /usr/share/webr/html
  volumeClaimTemplates:
  - metadata:
      name: webr-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi

