apiVersion: v1
kind: Service
metadata:
  name: webr-service-ninestrong
  labels:
    run: 9strong 
spec:
 # externalTrafficPolicy: Local #addition      #addition 1212
  clusterIP: None
  ports:
  #- port: 8081
  # name: webr-two
  - port: 8080
    name: webr-ninestrong
  selector:
   run: 9strong
---
apiVersion: v1
kind: Service
metadata:
  name: ninestrong
  labels:
    app: 9strong
spec:
  type: NodePort
  ports:
  #- port: 8081
   # nodePort: 30375
   # protocol: TCP
   # targetPort: 8081
   # name: webr-two
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: webr-ninestrong
  selector:
    app: 9strong
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webr-ninestrong
  labels:
    app: 9strong
spec:
  serviceName: "webr-service-ninestrong"
  podManagementPolicy: Parallel # Default is OrderedReady
  replicas: 64 # Default is 1
  selector:
    matchLabels:
      app: 9strong # Has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: 9strong # Has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: webr-service-ninestrong
        image: nineonestrong:latest
        imagePullPolicy: Never #changed 120919
        ports:
        - containerPort: 8080
          name: webr-ninestrong
        volumeMounts:
        - name: webr-ninestrong-persistent-storage
          mountPath: /usr/share/webr/html
  volumeClaimTemplates:
  - metadata:
      name: webr-ninestrong-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi

